In [1]:
import numpy as np
import pandas as pd
import keras
import warnings
warnings.filterwarnings("ignore")

Using TensorFlow backend.


In [3]:
df= pd.read_csv("/home/samridhi/boatgang/dataset/data.csv", header=None, skiprows=1)
df.head()

0  1
0  ATCATTCCCGCTGTCCATAATGATATGTACCGCGATATAG  1
1  TGAAACAACGGCCGAGATATGTACCATTCAGTCCAACAGA  1
2  CCTCCCTGAGTAGGATTCCAGACGATATGTACCAATGACG  1
3  ATGATATGTACCGCACCTAGTCTATAACAGGCCGTTGGGT  1
4  TTCGGAAGGTGTGAGTTGGTCTGATATGTACCCTTACGTT  1

In [4]:
df.shape

(60000, 2)

In [5]:
temp_sequences=df[0]
temp_target=df[1]

In [6]:
dict_i = {"A" : 0, "C": 1, "G": 2, "T" : 3}

In [7]:
def one_hot_encode(s):
    i=0
    ohe = np.zeros((len(s), 4))
    for k in s:
        ohe[i,dict_i[k]] = 1
        i+=1
    return ohe

In [8]:
ohe_sequences = np.array([one_hot_encode(s) for s in temp_sequences])

[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]


In [29]:
from keras.models import model_from_json, load_model, model_from_config
import json
k = '{"layers": [{"W_constraint": null, "b_constraint": null, "name": "Convolution1D", "custom_name": "convolution1d", "border_mode": "valid", "activation": "relu", "trainable": true, "input_shape": [200, 4], "W_learning_rate_multiplier": null, "filter_length": 19, "cache_enabled": true, "init": "uniform", "nb_filter": 40, "input_dim": null, "subsample_length": 1, "b_learning_rate_multiplier": null, "b_regularizer": null, "W_regularizer": null, "activity_regularizer": null, "input_length": null}, {"pool_length": 10, "name": "MaxPooling1D", "custom_name": "maxpooling1d", "stride": 10, "trainable": true, "cache_enabled": true, "border_mode": "valid"}, {"cache_enabled": true, "trainable": true, "name": "Flatten", "custom_name": "flatten"}, {"W_constraint": null, "b_constraint": null, "name": "Dense", "custom_name": "dense", "activity_regularizer": null, "trainable": true, "W_learning_rate_multiplier": null, "cache_enabled": true, "init": "glorot_uniform", "activation": "relu", "input_dim": null, "b_learning_rate_multiplier": null, "b_regularizer": null, "W_regularizer": null, "output_dim": 250}, {"cache_enabled": true, "trainable": true, "name": "Dropout", "custom_name": "dropout", "p": 0.5}, {"W_constraint": null, "b_constraint": null, "name": "Dense", "custom_name": "dense", "activity_regularizer": null, "trainable": true, "W_learning_rate_multiplier": null, "cache_enabled": true, "init": "glorot_uniform", "activation": "sigmoid", "input_dim": null, "b_learning_rate_multiplier": null, "b_regularizer": null, "W_regularizer": null, "output_dim": 1}], "optimizer": {"beta_1": 0.8999999761581421, "epsilon": 1e-08, "beta_2": 0.9990000128746033, "lr": 0.0010000000474974513, "name": "Adam"}, "class_mode": "binary", "name": "Sequential", "loss": "binary_crossentropy"}'
content = json.dumps(k)

In [30]:
model = model_from_json(content)

ValueError: Unknown layer:{"layers": [{"W_constraint": null, "b_constraint": null, "name": "Convolution1D", "custom_name": "convolution1d", "border_mode": "valid", "activation": "relu", "trainable": true, "input_shape": [200, 4], "W_learning_rate_multiplier": null, "filter_length": 19, "cache_enabled": true, "init": "uniform", "nb_filter": 40, "input_dim": null, "subsample_length": 1, "b_learning_rate_multiplier": null, "b_regularizer": null, "W_regularizer": null, "activity_regularizer": null, "input_length": null}, {"pool_length": 10, "name": "MaxPooling1D", "custom_name": "maxpooling1d", "stride": 10, "trainable": true, "cache_enabled": true, "border_mode": "valid"}, {"cache_enabled": true, "trainable": true, "name": "Flatten", "custom_name": "flatten"}, {"W_constraint": null, "b_constraint": null, "name": "Dense", "custom_name": "dense", "activity_regularizer": null, "trainable": true, "W_learning_rate_multiplier": null, "cache_enabled": true, "init": "glorot_uniform", "activation": "relu", "input_dim": null, "b_learning_rate_multiplier": null, "b_regularizer": null, "W_regularizer": null, "output_dim": 250}, {"cache_enabled": true, "trainable": true, "name": "Dropout", "custom_name": "dropout", "p": 0.5}, {"W_constraint": null, "b_constraint": null, "name": "Dense", "custom_name": "dense", "activity_regularizer": null, "trainable": true, "W_learning_rate_multiplier": null, "cache_enabled": true, "init": "glorot_uniform", "activation": "sigmoid", "input_dim": null, "b_learning_rate_multiplier": null, "b_regularizer": null, "W_regularizer": null, "output_dim": 1}], "optimizer": {"beta_1": 0.8999999761581421, "epsilon": 1e-08, "beta_2": 0.9990000128746033, "lr": 0.0010000000474974513, "name": "Adam"}, "class_mode": "binary", "name": "Sequential", "loss": "binary_crossentropy"}